// <auto-generated />
namespace ICA_01_2015ICT36.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatestaff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatestaff));
        
        string IMigrationMetadata.Id
        {
            get { return "202010210643217_updatestaff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
