// <auto-generated />
namespace ICA_01_2015ICT36.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class companydb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(companydb));
        
        string IMigrationMetadata.Id
        {
            get { return "202010141641384_companydb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
